name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app
      - name: Build and tests
	working-directory: ./LeBaluchon
        run:  xcodebuild clean test -project LeBaluchon.xcodeproj -scheme "LeBaluchon/" -destination "name=iPhone 8 Plus,OS=15.0"

